#!/bin/bash
# Tarih atamalari
gun=$(date +%d)               # bugun
gun1=$(date +%d -d "+1 day") # yarin
gun2=$(date +%d -d "+2 day") # ertesi gun
gun3=$(date +%d -d "+3 day") # 
gun4=$(date +%d -d "+4 day") # 

ay=$(date +%m)               # bu ay
ay1=$(date +%m -d "+1 day")  # yarinki ay
ay2=$(date +%m -d "+2 day")  # oburgunku  ay
ay3=$(date +%m -d "+3 day")  # 

tamyil=$(date +%Y)               # bu yil
tamyil1=$(date +%Y -d "+1 day")  # yarinki yil
tamyil2=$(date +%Y -d "+2 day")  # oburhunku yil
tamyil3=$(date +%Y -d "+3 day")  # oburhunku yil

#namelist.ARWpost yazilmasi
sed -i '1c &datetime ' namelist.ARWpost
sed -i '2c  start_date =  '\'$tamyil-$ay-$gun'_'00:00:00\'',  ' namelist.ARWpost  # ustten kesme icin '\
sed -i '3c end_date =  '\'$tamyil3-$ay3-$gun3'_'00:00:00\'',  ' namelist.ARWpost
sed -i '4c interval_seconds = 3600,' namelist.ARWpost
sed -i '5c tacc = 0,' namelist.ARWpost
sed -i '6c debug_level = 0,' namelist.ARWpost
sed -i '7c /' namelist.ARWpost
sed -i '8c \ ' namelist.ARWpost # bos satir ekleme
sed -i '9c  &io  ' namelist.ARWpost
sed -i '10c   input_root_name = '\'/home/hava12/Build_WRF/WRFV3/run/wrfout_d01_$tamyil-$ay-$gun'_'00.nc\''  ' namelist.ARWpost
sed -i '11c   output_root_name = '\'$tamyil-$ay-$gun'_'00\''  ' namelist.ARWpost
sed -i '12c plot =   '\'all_list\'' ' namelist.ARWpost
sed -i '13c fields =  '\'height\,pressure\,tk\,tc\'' ' namelist.ARWpost
sed -i '14c mercator_defs = .true. ' namelist.ARWpost
sed -i '15c /' namelist.ARWpost
sed -i '16c \ ' namelist.ARWpost # bos satir ekleme
sed -i '17c split_output = .true. ' namelist.ARWpost
sed -i '18c  frames_per_outfile = 2 ' namelist.ARWpost
sed -i '19c  plot = '\'all\'' ' namelist.ARWpost
sed -i '20c  plot = '\'list\'' ' namelist.ARWpost
sed -i '21c  plot = '\'all_list\'' ' namelist.ARWpost
sed -i '22c \! Below is a list of all available diagnostics ' namelist.ARWpost
sed -i '23c fields = '\'height\,geopt\,theta\,tc\,tk\,td\,td2\,rh\,rh2\,umet\,vmet\,pressure\,u10m\,v10m\,wdir\,wspd\,wd10\,ws10\,slp\,mcape\,mcin\,lcl\,lfc\,cape\,cin\,dbz\,max_dbz\,clfr\'' ' namelist.ARWpost
sed -i '24c \ ' namelist.ARWpost # bos satir ekleme
sed -i '25c \ ' namelist.ARWpost # bos satir ekleme
sed -i '26c &interp ' namelist.ARWpost 
sed -i '27c interp_method = 0, ' namelist.ARWpost 
sed -i '28c interp_levels = 1000.\,950.\,900.\,850.\,800.\,750.\,700.\,650.\,600.\,550.\,500.\,450.\,400.\,350.\,300.\,250.\,200.\,150.\,100.\, ' namelist.ARWpost 
sed -i '29c /' namelist.ARWpost
sed -i '30c \ ' namelist.ARWpost # bos satir ekleme
sed -i '31c extrapolate = .true. ' namelist.ARWpost 
sed -i '32c interp_method = 0\,  \! 0 is model levels\, -1 is nice height levels\, 1 is user specified pressure\/height ' namelist.ARWpost 
sed -i '33c  interp_levels = 1000.\,950.\,900.\,850.\,800.\,750.\,700.\,650.\,600.\,550.\,500.\,450.\,400.\,350.\,300.\,250.\,200.\,150.\,100.\, ' namelist.ARWpost 
sed -i '34c  interp_levels = 0.25\, 0.50\, 0.75\, 1.00\, 2.00\, 3.00\, 4.00\, 5.00\, 6.00\, 7.00\, 8.00\, 9.00\, 10.0\, 11.0\, 12.0\, 13.0\, 14.0\, 15.0\, 16.0\, 17.0\, 18.0\, 19.0\, 20.0\,' namelist.ARWpost 
